job.type: train
dataset.name: biokg_no_split

random_seed:
  default: 42
  torch: 42
  numpy: 42
  numba: 42
  python: 42

model: rotate
lookup_embedder:
  dim: 413

train:
  split: train
  type: negative_sampling
  loss: margin_ranking
  max_epochs: 800
  batch_size: 256 
  optimizer: Adagrad
  optimizer_args:
    lr: 0.055
  visualize_graph: True

negative_sampling:
  num_samples:
    s: 25
    p: 0          
    o: -1 # -1 means: same as s
  filtering:
    s: True
    o: True
    implementation: fast_if_available

valid:
  split: valid
  every: 5

eval:
  split: valid
  batch_size: 16