name: kge_playground
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - blas=1.0
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cryptography=39.0.0
  - cycler=0.11.0
  - docker-pycreds=0.4.0
  - freetype=2.12.1
  - gitdb=4.0.10
  - gitpython=3.1.30
  - icu=67.1
  - idna=3.4
  - kiwisolver=1.4.4
  - ld_impl_linux-64=2.39
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.32.1
  - libzlib=1.2.13
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - ncurses=6.3
  - numexpr=2.8.4
  - numpy=1.24.1
  - openssl=3.0.7
  - packaging=22.0
  - pandas=1.4.4
  - pathtools=0.1.2
  - pip=22.3.1
  - protobuf=4.21.12
  - psutil=5.9.4
  - pycparser=2.21
  - pydantic=1.10.4
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.8.2
  - python-dotenv=0.21.1
  - python_abi=3.8
  - pytz=2022.7
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.28.2
  - sentry-sdk=1.14.0
  - setproctitle=1.3.2
  - setuptools=66.1.1
  - six=1.16.0
  - smmap=3.0.5
  - tk=8.6.12
  - tornado=6.2
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wandb=0.13.9
  - wheel=0.38.4
  - xz=5.2.6
  - yaml=0.2.5
  - pip:
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - pillow==9.4.0
    - torch==1.13.1
    - torchaudio==0.13.1
    - torchvision==0.14.1