name: kge
channels:
  - defaults
  - pip
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - ncurses=6.3
  - openssl=1.1.1t
  - python=3.10.4
  - readline=8.1.2
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2022g
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - argparse==1.4.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - attrs==22.2.0
    - ax-platform==0.2.10
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - botorch==0.8.0
    - certifi==2022.12.7
    - cffi==1.15.1
    - charset-normalizer==3.0.1
    - comm==0.1.2
    - configspace==0.6.1
    - contextlib2==21.6.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - exceptiongroup==1.1.0
    - execnet==1.9.0
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - fqdn==1.5.1
    - gpytorch==1.9.0
    - greenlet==2.0.2
    - hpbandster==0.7.4
    - idna==3.4
    - igraph==0.10.4
    - iniconfig==2.0.0
    - ipykernel==6.21.2
    - ipython==8.10.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.3
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-client==8.0.3
    - jupyter-core==5.2.0
    - jupyter-events==0.6.3
    - jupyter-server==2.3.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.2
    - linear-operator==0.2.0
    - llvmlite==0.39.1
    - markupsafe==2.1.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - mock==5.0.1
    - more-itertools==9.0.0
    - multipledispatch==0.6.0
    - nbclassic==0.5.1
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - netifaces==0.11.0
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numba==0.56.4
    - numpy==1.23.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - opt-einsum==3.3.0
    - packaging==23.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - path==16.6.0
    - path-py==12.5.0
    - patsy==0.5.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - pip==22.3.1
    - platformdirs==3.0.0
    - plotly==5.13.0
    - pluggy==1.0.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.36
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyro-api==0.1.2
    - pyro-ppl==1.8.4
    - pyro4==4.82
    - pyrsistent==0.19.3
    - pytest==7.2.1
    - pytest-shutil==1.7.0
    - python-dateutil==2.8.2
    - python-graphviz==0.20.1
    - python-json-logger==2.0.6
    - pytz==2022.7.1
    - pyyaml==6.0
    - pyzmq==25.0.0
    - requests==2.28.2
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scikit-learn==1.2.1
    - scipy==1.10.0
    - send2trash==1.8.0
    - serpent==1.41
    - setuptools==65.6.3
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - sqlalchemy==1.4.46
    - stack-data==0.6.2
    - statsmodels==0.13.5
    - tenacity==8.2.1
    - termcolor==2.2.0
    - terminado==0.17.1
    - texttable==1.6.7
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torch==1.13.1
    - torchaudio==0.13.1
    - torchvision==0.14.1
    - torchviz==0.0.2
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.9.0
    - typeguard==2.13.3
    - typing-extensions==4.5.0
    - uri-template==1.2.0
    - urllib3==1.26.14
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - widgetsnbextension==3.6.2