dataset_configs:
  datasets_dir: kge/data
  tasks:
    - ddi_minerals
  train_frac: 0.8
  valid_frac: 0.1
model_configs:
  model_type: "complex"
  hidden_size: 512
  batch_size: 512
  grad_clip: 1
  learning_rate: 1e-4
  pretrained_path: models/link_prediction/complex/biokg/model_best.pt
  pretrained_entity_ids_path: biokg/entity_ids.del
testing_configs:
  epochs: 100
  freeze_embedding: True
  device: 0
  random_seed: 1234
  outputs_dir: "outputs"