dataset_config:
  dataset_name: "dsi-bdi-biokg"
  datasets_dir: "datasets/biokg"
  train_frac: 0.8
  valid_frac: 0.1
  neg_sampling_strat: "uniform"
model_config:
  model_type: "complex"
  embedding_size: 512
training_config:
  epochs: 20
  batch_size: 512
  regularizers:
    - type: n3
      coeff: 1e-2
    - type: f2
      coeff: 0
  optimizer: "adagrad"
  learning_rate: 0.1
  loss_fn: "1vsAll"
  grad_accumulation_step: 1
  score_rhs: True
  score_lhs: True
  score_rel: True
  eval_steps: 1
  device: 0
  random_seed: 1234
  outputs_dir: "outputs"