job.type: train
job.auto_correct: True
dataset.name: biokg
random_seed:
  default: -1
  numba: -1
  numpy: -1
  python: -1
  torch: -1

import:
- complex
- reciprocal_relations_model
complex:
  class_name: ComplEx
  entity_embedder:
    +++: +++
    dropout: -0.18433461524546146
    regularize_weight: 5.739933905238503e-19
    space: complex
    type: lookup_embedder
  relation_embedder:
    +++: +++
    dropout: 0.3942223796620965
    regularize_weight: 2.677586021605096e-08
    space: complex
    type: lookup_embedder
lookup_embedder:
  class_name: LookupEmbedder
  dim: 1024
  dropout: 0.0
  initialize: xavier_normal_
  initialize_args:
    +++: +++
    normal_:
      mean: 0.0
      std: 0.10460778997859611
    uniform_:
      a: -0.7974890093011315
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  normalize:
    p: -1.0
  pretrain:
    ensure_all: false
    model_filename: ''
  regularize: lp
  regularize_args:
    +++: +++
    p: 2
    weighted: true
  regularize_weight: 0.0
  round_dim_to: []
  space: euclidean
  sparse: false
reciprocal_relations_model:
  base_model:
    +++: +++
    type: complex
  class_name: ReciprocalRelationsModel
model: reciprocal_relations_model

train:
  abort_on_nan: true
  batch_size: 128
  checkpoint:
    every: 5
    keep: 3
    keep_init: true
  loss: kl
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    +++: +++
    factor: 0.95
    mode: max
    patience: 9
    threshold: 0.0001
  lr_warmup: 0
  max_epochs: 400
  num_workers: 0
  optimizer:
    +++: +++
    default:
      args:
        +++: +++
        lr: 0.5023877199659941
      type: Adagrad
  split: train
  subbatch_auto_tune: false
  subbatch_size: -1
  trace_level: epoch
  type: 1vsAll
  visualize_graph: false

valid:
  split: valid
  early_stopping:
    patience: 10
    threshold:
      epochs: 50
      metric_value: 0.05
  every: 2
  last: true
  metric: mean_reciprocal_rank_filtered_with_test

eval:
  split: test
  batch_size: 256
  type: entity_ranking